name: Create Release from Tag

on:
    push:
        tags:
            - v*.*.*

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@master
              with:
                ref: main
                fetch-depth: 0
            - name: Set up Go
              uses: actions/setup-go@master
              with:
                  go-version: '1.22.5'
            - name: Installing Packages
              run: go mod tidy
            - name: Build Project
              run: make all
            - name: Set up Node
              uses: actions/setup-node@master
              with:
                  node-version: 'lts/*'
                  registry-url: 'https://registry.npmjs.org'
            - name: Update Package Version
              run: |
                VERSION=$(git describe --tags --abbrev=0)
                npm version --no-git-tag-version $VERSION
            - name: Push Changes
              run: |
                git checkout main
                git config --global user.name 'github-actions[bot]'
                git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                git add package.json
                git commit -m "Updating Version..."
                git push
            - name: Publish Package
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: Create Release
              uses: softprops/action-gh-release@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Upload Assets
              uses: alexellis/upload-assets@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  asset_paths: '["./bin/*"]'
